import turtle

wn = turtle.Screen()
wn.setworldcoordinates(-20, -100, 300, 300)
t = turtle.Turtle()
x = t.xcor()
y = t.ycor()
t.speed(2)
t.shape("circle")
t.fillcolor("red")
c = turtle.Turtle()
c.penup()
c.goto(x+205, y+10)
c.speed(1)
c.shape("circle")
c.fillcolor("blue")
t.up()
c.left(45)
t.forward(200)
# my_start = (-50, 50)
# c.setx(my_start[0])
# c.sety(my_start[1])
c.forward(100)
c.up()

wn.exitonclick()